version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.3
    - 2.0.4
    - 2.1.1
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: gatsby-remark-embed-video
    versions:
    - 3.0.12
    - 3.1.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: preact
    versions:
    - 10.5.12
  - dependency-name: "@types/cors"
    versions:
    - 2.8.9
